=head1 NAME

campus_details

=head1 DESCRIPTION

Return information details about a specified campus.

=head2 Parameters

=over 4

=item region

Required. Name of region of campus. Example: C<region=aja>.

=item campus

Required. Name of campus. Example: C<campus=tai>.

=back

=head2 Sample Calls

  http://efsapi.example.com/api/v1/campus_details?region=aja;campus=tai

=head2 Sample Results

  {
     "status" : "Success",
     "result" : {
        "campus" : "tai",
        "region" : "aja",
        "attributes" : {
           "description" : "Taipei, Taiwan"
        },
        "locations" : [
           {
              "name" : "tun",
              "cells" : [
                 {
                    "disabled" : "0",
                    "name" : "p.tun.tai.aja.example.com",
                    "celltype" : "prod",
                    "hidden" : "0"
                 }
              ]
           },
           {
              "name" : "lun",
              "cells" : [
                 {
                    "disabled" : "0",
                    "name" : "d.lun.tai.aja.example.com",
                    "celltype" : "dev",
                    "hidden" : "0"
                 },
                 {
                    "disabled" : "0",
                    "name" : "p.lun.tai.aja.example.com",
                    "celltype" : "prod",
                    "hidden" : "0"
                 }
              ]
           }
        ]
     }
  }

